import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/react/index.ts',
    'src/stores/index.ts',
    'src/stores/r2.ts',
    'src/stores/http.ts',
    'src/stores/mock.ts',
    'src/stores/multi.ts',
    'src/stores/s3.ts',
    'src/stores/gcs.ts',
    'src/server/index.ts',
    'src/test/conformance.ts',
    'src/sqlite/vfs.ts',
    'src/sqlite/db.ts',
    'src/sqlite/tableSource.ts',
    'src/renderers/table.ts',
    'src/renderers/tableSource.ts',
    'src/renderers/tableControls.tsx',
    'src/renderers/tableSort.ts',
    'src/renderers/yaml.tsx',
    'src/renderers/parquet.tsx',
    'src/renderers/parquetData.ts',
    'src/renderers/markdown.tsx',
    'src/renderers/csv.tsx',
    'src/renderers/csvData.ts',
    'src/renderers/notebook.tsx',
    'src/renderers/code.tsx',
    'src/renderers/json.tsx',
    'src/url-state/index.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'react-router-dom',
    'hyparquet',
    'react-markdown',
    'remark-gfm',
    'highlight.js',
    'jq-web',
    'wa-sqlite',
    'use-prms',
  ],
})
