/** Demo fixture for MockStore. Designed to look like a realistic
 *  data-bucket layout — same shape consumers (ctbk, crashes) browse
 *  in production. */
import { CATALOG_SQLITE } from './catalog'
import { TREEMAPS_PDF } from './paper'
import { EVENTS_PARQUET } from './parquet'

export const DEMO_FIXTURE = {
  'README.md': '# @rdub/file-tree demo\n\nThis is a `MockStore`-backed file browser. ' +
    'Everything you see is in-memory, defined in `site/src/fixtures/demo.ts`.\n\n' +
    'Click around to navigate, use the filter to narrow listings, and try opening ' +
    'a text file to see the `<TextViewer>` in action.\n',
  'docs/intro.md': [
    '# Introduction',
    '',
    'file-tree exposes a minimal `Store` interface and a React `<FileTree>` component that adapts to any implementation.',
    '',
    '## What you can do here',
    '',
    '- **Browse**: folders list their recursive sizes; the treemap (split view) shows where the bytes are.',
    '- **Search**: press ⌘K (or the search button) for fuzzy path search across the whole tree.',
    '- **Preview**: markdown, CSV, parquet, SQLite, JSON/YAML, notebooks, PDFs and logs each open in a viewer.',
    '',
    'Start with [`samples/events.parquet`](/mock/samples/events.parquet) for the richest table, or [`data/`](/mock/data/) for small CSVs.',
    '',
  ].join('\n'),
  'docs/guide/setup.md': [
    '# Setup',
    '',
    '```bash',
    'pnpm add @rdub/file-tree',
    '```',
    '',
    'Then pick a `Store` and mount the browser:',
    '',
    '```tsx',
    "import { FileTree } from '@rdub/file-tree/react'",
    "import { R2Store } from '@rdub/file-tree/stores/r2'",
    '',
    'const store = R2Store(env.BUCKET)',
    '<FileTree store={store} routeBase="/files" />',
    '```',
    '',
    'See the README for the full snippet, including the server handlers.',
    '',
  ].join('\n'),
  'docs/guide/usage.md': [
    '# Usage',
    '',
    '| To… | Use |',
    '| --- | --- |',
    '| decorate a listing cell | `renderCell` |',
    '| format a table column | `renderCell` / `cellProps` on the viewer |',
    '| keep filter/sort/page in the URL | `useUrlPersistedState` |',
    '| show recursive sizes + treemap | `treeSource={walkTreeSource(store)}` |',
    '| add ⌘K path search | `treePathEndpoint` + `use-kbd` |',
    '',
  ].join('\n'),
  // A real, on-theme PDF so the `<PdfViewer>` (iframe, native Chrome
  // render) shows genuine content: a one-page note on squarified
  // treemaps — the very algorithm this demo's map uses — generated by
  // `tools/build-paper.mjs`. `MockStore` reports no content-type; the
  // viewer forces `application/pdf` so the iframe renders it inline.
  'docs/squarified-treemaps.pdf': TREEMAPS_PDF,
  'data/2024/q1.csv': 'date,value\n2024-01-01,100\n2024-02-01,150\n2024-03-01,200\n',
  'data/2024/q2.csv': 'date,value\n2024-04-01,180\n2024-05-01,220\n2024-06-01,260\n',
  'data/2025/q1.csv': 'date,value\n2025-01-01,300\n2025-02-01,330\n2025-03-01,360\n',
  'data/2025/q2.csv': 'date,value\n2025-04-01,400\n2025-05-01,440\n',
  // FK-link targets: `MockDemo`'s parquet `renderCell` turns the
  // `region` column into links to these, so a cell click navigates to
  // another file in the same tree.
  'docs/regions/nyc.md': [
    '# NYC',
    '',
    'New York City, one of the three regions `events.parquet` rows are tagged with.',
    '',
    '| | |',
    '| --- | --- |',
    '| Timezone | `America/New_York` |',
    '| Center | 40.71, -74.01 |',
    '| Events | rows tagged `nyc` in [`events.parquet`](/mock/samples/events.parquet) |',
    '',
  ].join('\n'),
  'docs/regions/sfo.md': [
    '# SFO',
    '',
    'San Francisco. Shares a timezone with LAX, so the two interleave in time-sorted views.',
    '',
    '| | |',
    '| --- | --- |',
    '| Timezone | `America/Los_Angeles` |',
    '| Center | 37.77, -122.42 |',
    '| Events | rows tagged `sfo` in [`events.parquet`](/mock/samples/events.parquet) |',
    '',
  ].join('\n'),
  'docs/regions/lax.md': [
    '# LAX',
    '',
    'Los Angeles, the southernmost of the three regions.',
    '',
    '| | |',
    '| --- | --- |',
    '| Timezone | `America/Los_Angeles` |',
    '| Center | 34.05, -118.24 |',
    '| Events | rows tagged `lax` in [`events.parquet`](/mock/samples/events.parquet) |',
    '',
  ].join('\n'),
  // A spread of sizes so the treemap is non-trivial: one dominant day (an
  // error storm), a couple of mid-size days, and a few quiet ones — enough
  // tiles at enough different areas to exercise squarify + the brush styles.
  'logs/2026-01-01.log': '[INFO] System started\n[DEBUG] Connected to db\n',
  'logs/2026-01-02.log': '[INFO] Processing batch 1\n[INFO] Processing batch 2\n',
  'logs/2026-01-03.log': Array.from({ length: 40 }, (_, i) =>
    `[ERROR] request ${1000 + i} failed: upstream timeout after 30s (retry ${i % 3})`,
  ).join('\n') + '\n',
  'logs/2026-01-04.log': Array.from({ length: 14 }, (_, i) =>
    `[WARN] queue depth ${120 + i * 7} exceeds soft limit; shedding load`,
  ).join('\n') + '\n',
  'logs/2026-01-05.log': '[INFO] Nightly compaction started\n' +
    '[INFO] Compacted 3 segments (-> 1)\n[INFO] Reclaimed 412 MB\n[INFO] Done in 8.4s\n',
  'logs/2026-01-06.log': Array.from({ length: 24 }, (_, i) =>
    `[INFO] batch ${i} ok (${90 + i} rows, ${(i * 1.3).toFixed(1)}ms)`,
  ).join('\n') + '\n',
  'logs/2026-01-07.log': '[INFO] Idle\n',
  // Deliberately 4 levels deep (root → server → tls → ciphers): the JSON
  // viewer's `initialOpenDepth` and expand-all behavior are only
  // meaningfully exercised by nesting.
  'config.json': JSON.stringify({
    version: '0.0.1',
    demo: true,
    server: {
      host: 'localhost',
      tls: { enabled: false, ciphers: ['aes', 'chacha'] },
    },
  }, null, 2) + '\n',
  // Exercises what YAML has that JSON doesn't: comments, anchors and
  // aliases, block scalars, and native dates. The comments are the
  // interesting ones — `yaml.parse()` drops them, since they aren't in
  // the data model, so a tree of parsed values loses them silently
  // unless the renderer goes out of its way.
  'config.yaml': [
    '# Demo config — the tree viewer parses this, so YAML gets the same',
    '# collapsible nodes, search, depth controls and jq as JSON.',
    'version: 0.0.1   # inline comments attach to the line above them',
    'demo: true',
    '',
    '# Anchors let a block be named once and reused. `defaults` is the',
    '# anchor; the two servers below alias it.',
    'defaults: &defaults',
    '  retries: 3',
    '  timeout: 30',
    '',
    'servers:',
    '  - <<: *defaults',
    '    name: mock',
    '  - <<: *defaults',
    '    name: http',
    '    timeout: 60   # overrides the alias',
    '',
    '# Block scalars keep newlines (|) or fold them (>).',
    'notes: |',
    '  A literal block.',
    '  Newlines are preserved.',
    '',
    'released: 2026-04-25   # a native date, not a string',
    'sources:',
    '  - mock',
    '  - http',
    '',
  ].join('\n'),
  // Exercises the parquet viewer's timestamp inference — see
  // `./parquet.ts` for what each column is meant to prove.
  // A whole database, browsed table by table. Unlike every other
  // fixture here it is never read whole: the viewer asks SQLite for a
  // page and SQLite asks the store for the few 8 KiB blocks that page
  // lives in.
  'samples/catalog.sqlite': CATALOG_SQLITE,
  'samples/events.parquet': EVENTS_PARQUET,
  // Same bytes, second extension: `MockDemo` registers `.pqt` with
  // `fullLoadMaxBytes: 0` so the streaming half of small-table mode —
  // row-group pruning from footer statistics — is demoed on real data
  // rather than only unit-tested.
  'samples/events.pqt': EVENTS_PARQUET,
}
